/* eslint-disable react/no-unescaped-entities */
/* eslint-disable no-undef */
import React from 'react';
import {
  Box,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Container,
  Divider,
} from '@mui/material';
import { Security, DeveloperMode, VerifiedUser, Build } from '@mui/icons-material';

const ExploreFeaturesPage = () => {
  const features = [
    {
      icon: <Security sx={{ color: 'primary.main', fontSize: '3rem', mb: 2 }} />,
      title: 'JWT with Refresh Tokens',
      description:
        'Secure session management with short-lived access tokens and long-lived refresh tokens generated by the server.',
      highlights: ['JWT Tokens', 'Access/Refresh Token Pairing', 'Bcrypt Hashing'],
    },
    {
      icon: <DeveloperMode sx={{ color: 'primary.main', fontSize: '3rem', mb: 2 }} />,
      title: 'Full-Stack Integration',
      description:
        'Built with React, Node.js, PostgreSQL, and Material-UI for a seamless, production-ready full-stack solution.',
      highlights: ['React UI', 'Express Backend', 'PostgreSQL Database', 'Knex', 'Migrations'],
    },
    {
      icon: <VerifiedUser sx={{ color: 'primary.main', fontSize: '3rem', mb: 2 }} />,
      title: 'Automated Testing',
      description:
        'Includes unit, integration, and end-to-end tests for high reliability during every deployment.',
      highlights: ['Jest/Supertest', 'Cypress', 'Unit/Integration/E2E', 'Code Coverage > 80%'],
    },
    {
      icon: <Build sx={{ color: 'primary.main', fontSize: '3rem', mb: 2 }} />,
      title: 'Environment-Specific Logging',
      description:
        'Configured logging for different environments to ensure traceability and debugging efficiency.',
      highlights: ['Winston Logger', 'Custom Log Levels', 'Structured JSON Logging'],
    },
  ];

  return (
    <Box
      sx={{
        backgroundColor: 'background.default',
        color: 'text.primary',
        minHeight: '100vh',
        py: 6,
        px: 4,
      }}
    >
      {/* Hero Section */}
      <Container maxWidth="md" sx={{ textAlign: 'center', mb: 6 }}>
        <Typography variant="h3" sx={{ fontWeight: 'bold', mb: 3 }}>
          Explore Features
        </Typography>
        <Typography variant="h6" sx={{ color: 'text.secondary', mb: 2 }}>
          Dive deeper into the cutting-edge features that make this demo stand out.
        </Typography>
      </Container>

      {/* Features Section */}
      <Container maxWidth="lg">
        <Grid container spacing={4}>
          {features.map((feature, index) => (
            <Grid item xs={12} sm={6} md={3} key={index}>
              <Card
                sx={{
                  backgroundColor: 'background.paper',
                  color: 'text.primary',
                  height: '100%',
                  borderRadius: 2,
                  boxShadow: 2,
                }}
              >
                <CardContent
                  sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    textAlign: 'center',
                  }}
                >
                  {feature.icon}
                  <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 1 }}>
                    {feature.title}
                  </Typography>
                  <Typography variant="body2" sx={{ color: 'text.secondary', mb: 2 }}>
                    {feature.description}
                  </Typography>
                  <Divider sx={{ my: 2, width: '80%' }} />
                  <Typography variant="body2" sx={{ fontWeight: 'bold', mb: 1 }}>
                    Highlights
                  </Typography>
                  <ul style={{ listStyle: 'none', padding: 0 }}>
                    {feature.highlights.map((highlight, idx) => (
                      <li key={idx} style={{ margin: '5px 0', color: 'text.secondary' }}>
                        {highlight}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      {/* Call to Action */}
      <Container maxWidth="md" sx={{ textAlign: 'center', mt: 8 }}>
        <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 2 }}>
          Ready to see it in action?
        </Typography>
        <Typography variant="body1" sx={{ color: 'text.secondary', mb: 4 }}>
          Explore the live demo or check out the codebase on GitHub.
        </Typography>
        <Button
          variant="outlined"
          color="primary"
          href="/login"
          sx={{ mr: 2, textTransform: 'none', px: 4 }}
        >
          Try the Demo
        </Button>
        <Button
          variant="contained"
          color="primary"
          href="https://github.com/yermbiz/auth-flow-fullstack"
          sx={{ textTransform: 'none', px: 4 }}
        >
          View on GitHub
        </Button>
      </Container>
    </Box>
  );
};

export default ExploreFeaturesPage;
